package com.example.musicplayergo

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner

/**
 * Custom test runner that uses TestGoApp_Application instead of GoApp.
 *
 * This enables Hilt dependency injection in instrumented tests,
 * allowing TestDataModule to replace DataModule with FakeMusicRepository.
 *
 * The TestGoApp_Application is generated by Hilt from @CustomTestApplication annotation
 * and it extends TestGoAppBase which initializes GoPreferences.
 */
class HiltTestRunner : AndroidJUnitRunner() {

    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application {
        return super.newApplication(cl, TestGoApp_Application::class.java.name, context)
    }
}
